// This file is automatically generated. Do not edit it directly.
// Supabase client removed after migrating to Firebase. This file is kept to avoid
// import errors in any remaining files. If imported, it will throw to surface
// unintended usage. Remove all imports from "@/integrations/supabase/client".
export const supabase = new Proxy({}, {
  get() {
    throw new Error('Supabase has been removed. Use Firebase Firestore instead.');
  }
}) as unknown as any;